#define NUMSIG       32

#define SIGABRT	6
#define SIGALRM	14
#define SIGBUS	10
#define SIGCHLD	18
#define SIGCONT	25
#define SIGFPE	8
#define SIGHUP	1
#define SIGILL	4
#define SIGINT	2
#define SIGKILL	9
#define SIGPIPE	13
#define SIGQUIT	3
#define SIGSEGV	11
#define SIGSTOP	23
#define SIGTERM	15
#define SIGTSTP	23
#define SIGTTIN	26
#define SIGTTOU	27
#define SIGUSR1	16
#define SIGUSR2	17
#define SIGPOLL	22
#define SIGPROF	29
#define SIGSYS	12
#define SIGTRAP	5
#define SIGURG	21
#define SIGVTALRM 28
#define SIGXCPU	30
#define SIGXFSZ	31

typedef void (*sighandler_t)(void);